---

- name: "Include Zabbix gpg ids"
  include_vars: zabbix.yml

- name: "Set short version name"
  set_fact:
    zabbix_short_version: "{{ zabbix_version | regex_replace('\\.', '') }}"

- name: "Debian | Set some facts"
  set_fact:
    datafiles_path: /usr/share/zabbix-server-{{ database_type }}
  when:
    - zabbix_version is version_compare('3.0', '<')
  tags:
    - zabbix-server
    - init
    - config

- name: "Debian | Set some facts for Zabbix 3.0"
  set_fact:
    datafiles_path: /usr/share/doc/zabbix-server-{{ database_type }}
  when:
    - zabbix_version is version_compare('3.0', '>=')
  tags:
    - zabbix-server
    - init
    - config

- name: "Debian | Install gpg key"
  apt_key:
    id: "{{ sign_keys[zabbix_short_version][ansible_distribution_release]['sign_key'] }}"
    url: http://repo.zabbix.com/zabbix-official-repo.key
  when:
    - zabbix_repo == "zabbix"
  become: yes
  tags:
    - zabbix-server
    - init

- name: "Debian | Installing deb-src repository Ubuntu"
  apt_repository:
    repo: "deb-src http://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/ {{ ansible_distribution_release }} main"
    state: present
  when:
    - ansible_distribution == "Ubuntu"
    - zabbix_repo == "zabbix"
  become: yes
  tags:
    - zabbix-server
    - init

- name: "Debian | Installing deb repository Debian"
  apt_repository:
    repo: "deb http://repo.zabbix.com/zabbix/{{ zabbix_version }}/debian/ {{ ansible_distribution_release }} main"
    state: present
  when:
    - ansible_distribution == "Debian"
    - zabbix_repo == "zabbix"
  become: yes
  tags:
    - zabbix-server
    - init

- name: "Debian | Installing deb-src repository Debian"
  apt_repository:
    repo: "deb-src http://repo.zabbix.com/zabbix/{{ zabbix_version }}/debian/ {{ ansible_distribution_release }} main"
    state: present
  when:
    - ansible_distribution == "Debian"
    - zabbix_repo == "zabbix"
  become: yes
  tags:
    - zabbix-server
    - init

- name: "Debian | Installing deb repository Ubuntu"
  apt_repository:
    repo: "deb http://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/ {{ ansible_distribution_release }} main"
    state: present
  when:
    - ansible_distribution == "Ubuntu"
    - zabbix_repo == "zabbix"
  become: yes
  tags:
    - zabbix-server
    - init

- name: apt-get clean
  shell: apt-get clean; rm -rf /tmp/*; apt-get update
  args:
    warn: False
  changed_when: False
  tags:
    - skip_ansible_lint

- name: "Debian | Installing zabbix-server-{{ database_type }}"
  apt:
    pkg: zabbix-server-{{ database_type }}
    state: present
    update_cache: yes
    cache_valid_time: 0
  tags:
    - zabbix-server
    - init

- name: "Debian | Install Ansible module dependencies"
  apt:
    name: python-psycopg2
    state: present
  when:
    - zabbix_database_creation
  tags:
    - zabbix-server
    - init

- name: "Debian | Install Mysql Client package"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-client
    - python-mysqldb
  when:
    - database_type == 'mysql'
  tags:
    - zabbix-server
    - init
    - database

- name: "Debian | Install PostgreSQL Client package"
  apt:
    name: postgresql-client
    state: present
  when:
    - database_type == 'pgsql'
  tags:
    - zabbix-server
    - init
    - database
